Assignment 2: Data Structures, Functions, NumPy & Pandas

Name: Tausif Ali  
Batch: Data Science Weekday – Hyderabad  

Q1: Create a list of 5 integers and perform append, insert, remove, pop, and reverse operations.

In this question, we created a list of integers and applied different list operations.
The append() method adds an element at the end of the list, insert() adds an element at a specific position,
remove() deletes a specific value, pop() removes the last element, and reverse() changes the order of elements.
These operations help in modifying list data dynamically.

In [1]:
def list_operations():
    numbers = [10, 20, 30, 40, 50]

    numbers.append(60)
    numbers.insert(2, 25)
    numbers.remove(40)
    numbers.pop()
    numbers.reverse()

    print("Final List:", numbers)

list_operations()

Final List: [50, 30, 25, 20, 10]


This code uses different list methods to modify the list such as append, insert, remove, pop, and reverse.

Q2: Create a tuple and try to change one value.

A tuple is a data structure that stores multiple values, but it is immutable.
This means once a tuple is created, its elements cannot be changed.
When we try to modify an element, Python raises a TypeError.
This ensures data safety when values should not be altered.

In [2]:
def tuple_example():
    names = ("Alice", "Bob", "Charlie")

    try:
        names[1] = "David"
    except TypeError:
        print("Tuples cannot be modified")

tuple_example()

Tuples cannot be modified


Tuples are immutable, which means their values cannot be changed after creation.

Q3: Create two sets and perform union, intersection, and difference.

Sets are unordered collections that do not allow duplicate values.
In this example, union combines elements from both sets,
intersection finds common elements, and difference finds elements present in one set but not in the other.
These operations are useful when comparing datasets.

In [3]:
def set_operations():
    set1 = {1, 2, 3, 4}
    set2 = {3, 4, 5, 6}

    print("Union:", set1 | set2)
    print("Intersection:", set1 & set2)
    print("Difference:", set1 - set2)

set_operations()

Union: {1, 2, 3, 4, 5, 6}
Intersection: {3, 4}
Difference: {1, 2}


Set operations like union, intersection, and difference are used to compare elements between two sets.

Q4: Create a dictionary and update values.

Explanation:
A dictionary stores data in key-value pairs.
We updated the value of an existing key ("age") and added a new key ("email").
Dictionaries are flexible and allow easy modification and extension of data.

In [4]:
def update_dictionary():
    person = {
        "name": "John",
        "age": 25,
        "city": "New York"
    }

    person["age"] = 26
    person["email"] = "john@example.com"

    print("Updated Dictionary:", person)

update_dictionary()

Updated Dictionary: {'name': 'John', 'age': 26, 'city': 'New York', 'email': 'john@example.com'}


Dictionary values can be updated by using keys, and new key-value pairs can also be added.

Q5: Check if a person is eligible to vote.

Explanation:
This program checks whether a person is eligible to vote based on age.
Using an if-else condition, it compares the age with 18.
If the age is 18 or above, the person is eligible; otherwise, not eligible.
This demonstrates basic decision-making in Python.

In [5]:
def check_voting(age):
    if age >= 18:
        print("Eligible to vote")
    else:
        print("Not eligible to vote")

check_voting(20)

Eligible to vote


Q6: Calculate grade based on marks.

Explanation:
In this problem, multiple conditions are checked using if-elif-else statements.
Based on the marks, different grades are assigned.
This type of conditional logic is useful when there are multiple possible outcomes.

In [6]:
def calculate_grade(marks):
    if marks >= 90:
        print("Grade: A")
    elif marks >= 75:
        print("Grade: B")
    elif marks >= 50:
        print("Grade: C")
    else:
        print("Fail")

calculate_grade(85)

Grade: B


Multiple conditions are checked using if-elif-else to assign grades based on marks.

Q7: Check if number is positive, even, odd, or negative.

Explanation:
This code checks multiple conditions.
First, it determines whether the number is positive, negative, or zero.
If the number is positive, it further checks whether it is even or odd using the modulus operator (%).
This demonstrates nested conditional statements.

In [7]:
def number_check(num):
    if num > 0:
        if num % 2 == 0:
            print("Positive Even")
        else:
            print("Positive Odd")
    elif num < 0:
        print("Negative Number")
    else:
        print("Zero")

number_check(10)

Positive Even


The code checks if the number is positive, negative, or zero and also checks if it is even or odd.

In [9]:
import numpy as np

Q8: Create scalar, 1D array, and 2D array.

Explanation:
NumPy is used for numerical operations and array handling.
A scalar represents a single value, a 1D array is like a list, and a 2D array is like a matrix.
The reshape() function is used to convert a 1D array into a 2D structure.

In [11]:
def numpy_arrays():
    scalar = np.array(5)
    arr_1d = np.arange(1, 6)
    arr_2d = np.arange(10, 70, 10).reshape(2, 3)

    print("Scalar:", scalar)
    print("1D Array:", arr_1d)
    print("2D Array:\n", arr_2d)

numpy_arrays()

Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


NumPy is used to create arrays. A scalar is a single value, 1D array is a list of values, and 2D array is a matrix.

Q9: Generate a 4x4 random array.

Explanation:
A random 4x4 array is generated using NumPy.
The randint() function creates random integers within a given range.
This is useful in simulations, testing, and generating sample data.

In [12]:
def random_array():
    arr = np.random.randint(0, 101, (4, 4))
    print(arr)

random_array()

[[17 64  3  6]
 [29 73 73 76]
 [ 4 76  6 82]
 [89 98  7  0]]


A random 4x4 array is created using NumPy with values between 0 and 100.

Q10: Convert NumPy array to Pandas DataFrame.

Explanation:
In this step, a NumPy array is converted into a Pandas DataFrame.
A DataFrame is a tabular data structure with rows and columns.
Column names are assigned to make the data more readable and structured.

In [13]:
import pandas as pd

def numpy_to_dataframe():
    arr = np.arange(1, 10).reshape(3, 3)
    df = pd.DataFrame(arr, columns=["A", "B", "C"])

    print(df)

numpy_to_dataframe()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


A NumPy array is converted into a Pandas DataFrame with column names.

Q11: Perform operations on a DataFrame.

Explanation:
This program demonstrates basic data handling using Pandas.
A DataFrame is created with sample data.
The info() function shows dataset details, and describe() provides statistical summary.
Specific columns are selected, unnecessary columns are removed, missing values are filled using the mean,
and duplicate rows are removed.
These steps are part of data cleaning and preprocessing.

In [19]:
import pandas as pd

# Function to perform DataFrame operations
def pandas_operations():
    data = {
        "Name": ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
        "Age": [23, 25, 22, 24, 26, 28, 27, 29, 30, 31],
        "City": ["NY", "LA", "SF", "TX", "NY", "LA", "SF", "TX", "NY", "LA"],
        "Salary": [50000, 60000, None, 55000, 65000, None, 70000, 72000, 68000, 75000]
    }

    # Create DataFrame
    df = pd.DataFrame(data)

    # Display basic information
    print("Info:")
    df.info()

    # Display statistical summary
    print("\nSummary:")
    print(df.describe())

    # Select specific columns
    print("\nSelected Columns (Name and City):")
    print(df[["Name", "City"]])

    # Drop 'City' column
    df = df.drop("City", axis=1)

    # Fill missing values in Salary column (correct way, no warning)
    mean_salary = df["Salary"].mean()
    df["Salary"] = df["Salary"].fillna(mean_salary)

    # Remove duplicate rows
    df = df.drop_duplicates()

    # Display final DataFrame
    print("\nFinal DataFrame:")
    print(df)

# Call function
pandas_operations()

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

Summary:
            Age       Salary
count  10.00000      8.00000
mean   26.50000  64375.00000
std     3.02765   8700.36945
min    22.00000  50000.00000
25%    24.25000  58750.00000
50%    26.50000  66500.00000
75%    28.75000  70500.00000
max    31.00000  75000.00000

Selected Columns (Name and City):
  Name City
0    A   NY
1    B   LA
2    C   SF
3    D   TX
4    E   NY
5    F   LA
6    G   SF
7    H   TX
8    I   NY
9    J   LA

Final DataFrame:
  Name  Age   Salary
0    A   23  50000.0
1    B   25  60000.0
2    C   22  64375.0
3    D   24  55000.0
4    E   26  65000.0
5    F   28  64375.0
6


This code creates a DataFrame, shows information and summary, selects columns, removes a column, fills missing values, and removes duplicates.

Conclusion

In this assignment, I worked with Python data structures, conditional statements, NumPy arrays, and Pandas DataFrames.
I learned how to manipulate data, apply logical conditions, and perform basic data analysis.
This assignment helped improve my understanding of Python and data handling techniques.